import { Link } from 'react-router-dom';
import { ArrowRight, MapPin } from 'lucide-react';
import type { DriverStop, DriverTripDetail } from '@waypoint/shared';
import { clockLabel, driverLink, DriverChip, DriverFacts, DriverPanel, sentenceCase, stopVersions, timeLabel, type ExecuteDriverAction } from './components';

export function RoutePage({ trip, stop, params, selectStop, execute, busy, pendingStop }: {
  trip: DriverTripDetail; stop?: DriverStop; params: URLSearchParams; selectStop: (id: string) => void; execute: ExecuteDriverAction; busy: boolean; pendingStop: boolean;
}) {
  const outlet = stop?.order.outlet;
  return <><DriverPanel kicker="ACTUAL TRIP STOP SEQUENCE" title={`${trip.stopCount} delivery stops`}><ol className="driver-stop-list">{trip.stops.map(item => <li key={item.id}><button type="button" className={stop?.id === item.id ? 'selected' : ''} onClick={() => selectStop(item.id)}><span className="driver-stop-number">{item.sequence}</span><span><strong>{item.order.outlet.outletRef}</strong><small>{item.order.orderRef} · {item.loadedUnits} loaded units</small><small>{sentenceCase(item.status)}</small></span><DriverChip label={item.delivery ? 'Outcome recorded' : item.id === trip.nextStopId ? 'Current stop' : 'Route stop'} tone={item.delivery ? 'green' : item.id === trip.nextStopId ? 'blue' : 'gray'} /></button></li>)}</ol></DriverPanel>{stop && outlet && <DriverPanel kicker={`STOP ${stop.sequence} · ${stop.order.orderRef}`} title={outlet.outletRef} action={<DriverChip label={pendingStop ? 'Saved locally · pending sync' : sentenceCase(stop.status)} tone={pendingStop ? 'amber' : stop.delivery ? 'green' : 'blue'} />}><div className="driver-panel-body"><p className="driver-stop-subtitle">Waypoint {sentenceCase(outlet.brand)} · {outlet.district}</p><DriverFacts facts={[
    ['Originally ordered', `${stop.order.orderedUnits.toLocaleString()} units`], ['Actual loaded manifest', `${stop.loadedUnits.toLocaleString()} units`], ['Receiving window', `${clockLabel(outlet.deliveryWindowOpen)}–${clockLabel(outlet.deliveryWindowClose)}`], ['Planned arrival', stop.plannedArrival ? timeLabel(stop.plannedArrival) : 'Not recorded'], ['Access / dock', `${sentenceCase(outlet.accessConstraint)} · ${sentenceCase(outlet.dockType)}`], ['Temperature requirement', sentenceCase(stop.order.temperatureRequirement)]
  ]} />{stop.loadedUnits < stop.order.orderedUnits && <p className="driver-note warning">Dispatcher approved a revised loaded manifest: {stop.order.orderedUnits} originally ordered, {stop.loadedUnits} actually loaded. Deliver against the loaded quantity.</p>}{stop.exceptions.map(issue => <p key={issue.id} className={`driver-note ${issue.status === 'RESOLVED' ? 'success' : 'warning'}`}><strong>{sentenceCase(issue.type)} · {sentenceCase(issue.status)}</strong>{issue.message}</p>)}{stop.actualArrival && <p className={`driver-note ${pendingStop ? 'warning' : 'success'}`}>{pendingStop ? 'Local arrival / event' : 'Arrival recorded'} {timeLabel(stop.actualArrival)}.</p>}{stop.canArrive && <button type="button" className="btn primary driver-block" disabled={busy} onClick={() => void execute('ARRIVAL', stop.id, stopVersions(trip, stop))}>Record Arrival<MapPin size={17} /></button>}{stop.canComplete && <Link className="btn primary driver-block" to={driverLink('proof', params, { stop: stop.id })}>Record Delivery<ArrowRight size={17} /></Link>}{stop.delivery && <Link className="btn secondary driver-block" to={driverLink('proof', params, { stop: stop.id })}>View Recorded Proof<ArrowRight size={17} /></Link>}{!stop.canArrive && !stop.canComplete && !stop.delivery && <p className="driver-note">Start the trip and complete earlier stops before recording this delivery.</p>}<p className="driver-note">Use these controls while safely stopped. Arrival is recorded without GPS verification.</p></div></DriverPanel>}</>;
}
