import { RefreshCw, Wifi, WifiOff } from 'lucide-react';
import type { LocalDriverOperation } from '../offline/model';
import { DriverChip, DriverFacts, DriverPanel, sentenceCase, timeLabel } from './components';

export function SyncPage({ operations, online, syncing, syncNow, cacheSavedAt, shellReady }: {
  operations: LocalDriverOperation[]; online: boolean; syncing: boolean; syncNow: () => Promise<void>; cacheSavedAt: string | null; shellReady: boolean;
}) {
  const unsynced = operations.filter(item => item.syncStatus !== 'SYNCED');
  return <><section className="driver-sync-summary"><span>{online ? <Wifi size={27} /> : <WifiOff size={27} />}</span><div><h2>{online ? 'Connection available' : 'Offline'}</h2><p>{unsynced.length ? `${unsynced.length} saved operations still need server confirmation.` : operations.length ? 'Saved operations are synchronized.' : 'No delivery operations have been saved on this device.'}</p></div></section><DriverPanel kicker="OFFLINE READINESS" title="Route saved on this device"><div className="driver-panel-body"><DriverFacts facts={[[ 'Route cache', cacheSavedAt ? `Saved ${timeLabel(cacheSavedAt)}` : 'No route cached yet' ], ['Application shell', shellReady ? 'Available for offline reload' : 'Preparing offline shell'], ['Network', online ? 'Browser reports online' : 'Browser reports offline'], ['Pending work', String(unsynced.length)]]} /><p className="driver-note">Cached route data and pending actions are kept separately from shared server records. Failed or conflicted work remains on this device.</p><button type="button" className="btn primary driver-block" disabled={!online || syncing} onClick={() => void syncNow()}><RefreshCw size={17} />{syncing ? 'Syncing…' : 'Sync now'}</button></div></DriverPanel><DriverPanel kicker="DURABLE OPERATION QUEUE" title={`${operations.length} recorded operations`}><ol className="driver-operation-list">{operations.map(item => <li key={item.operationId}><header><strong>{sentenceCase(item.action)}</strong><DriverChip label={item.syncStatus === 'PENDING' ? 'Pending sync' : item.syncStatus === 'FAILED' ? 'Sync failed' : sentenceCase(item.syncStatus)} tone={item.syncStatus === 'CONFLICT' || item.syncStatus === 'FAILED' ? 'red' : item.syncStatus === 'SYNCED' ? 'green' : 'amber'} /></header><p>{item.entityType === 'TRIP_STOP' ? item.baseTrip?.stops.find(stop => stop.id === item.entityId)?.order.orderRef || 'Delivery stop' : item.baseTrip?.tripRef || 'Assigned trip'}</p><p>Saved {timeLabel(item.createdAt)}</p>{typeof item.payload.deliveredUnits === 'number' && <p>{item.payload.deliveredUnits} delivered units{typeof item.payload.recipientName === 'string' ? ` · ${item.payload.recipientName}` : ''}</p>}{typeof item.payload.driverNote === 'string' && <p>{item.payload.driverNote}</p>}{item.reason && <p className="driver-note warning" role="alert"><strong>{item.syncStatus === 'CONFLICT' ? 'Conflict retained' : 'Sync needs attention'}</strong>{item.reason}{item.serverVersion !== undefined && ` · Server version ${item.serverVersion}`}</p>}{item.syncStatus === 'CONFLICT' && <p className="driver-helper">Refresh the shared route and review this change with Dispatcher. The saved action will not overwrite changed server facts.</p>}{item.syncStatus === 'FAILED' && <p className="driver-helper">Reconnect and use Sync now to retry. This saved action is retained.</p>}</li>)}</ol>{!operations.length && <p className="driver-note driver-empty-queue">Arrival and delivery updates will appear here after recording them.</p>}</DriverPanel></>;
}
