import type { ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, CheckCircle2, Clock3, Package, Plus, TriangleAlert } from 'lucide-react';
import type { StoreOrderSummary } from '@waypoint/shared';
import { useStoreHome, useStoreOrder } from './api';
import { clockLabel, dateLabel, EmptyState, ErrorState, LoadingState, OrderRow, OrderTimeline, orderLink, OutletIdentity, Panel, sentenceCase, StatusChip } from './components';

function FeaturedOrder({ order, metrics }: { order: StoreOrderSummary; metrics: ReactNode }) {
  const detail = useStoreOrder(order.id);
  return <div className="store-home-layout"><div className="store-stack">{metrics}<Panel kicker="CURRENT ORDER" title={order.orderRef} action={<StatusChip status={order.status} />}><div className="store-panel-body"><dl className="store-facts"><div><dt>Requested delivery</dt><dd>{dateLabel(order.requestedDeliveryDate)}</dd></div><div><dt>Eligible run</dt><dd>{dateLabel(order.eligibleDeliveryDate)}</dd></div><div><dt>Originally ordered</dt><dd>{order.orderedUnits.toLocaleString()} units</dd></div><div><dt>Temperature</dt><dd>{sentenceCase(order.temperatureRequirement)}</dd></div><div><dt>Planned arrival</dt><dd>{order.plannedArrival ? <time dateTime={order.plannedArrival}>{new Intl.DateTimeFormat('en-LK', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Colombo' }).format(new Date(order.plannedArrival))}</time> : ['CONFIRMED', 'CLOSED_FOR_PLANNING'].includes(order.status) ? 'Awaiting planning' : 'Not recorded'}</dd></div><div><dt>Actually loaded</dt><dd>{order.loadedUnits === null ? 'Not recorded' : `${order.loadedUnits.toLocaleString()} units`}</dd></div></dl>{order.eligibilityNotice && <p className="store-note warning">{order.eligibilityNotice}</p>}<Link className="btn primary store-block" to={orderLink(order)}>Track Delivery<ArrowRight size={17} /></Link></div></Panel></div><Panel kicker="ORDER TIMELINE" title="Shared lifecycle">{detail.isPending ? <div className="store-panel-body store-inline-loading" role="status"><div className="loading-dot" />Loading recorded events…</div> : detail.isError ? <div className="store-panel-body"><p className="store-helper" role="alert">{detail.error.message}</p><button className="btn secondary" onClick={() => void detail.refetch()}>Retry timeline</button></div> : <OrderTimeline order={detail.data} />}</Panel></div>;
}

export function StoreHomePage() {
  const home = useStoreHome();
  if (home.isPending) return <LoadingState message="Loading your orders…" />;
  if (home.isError) return <ErrorState error={home.error} retry={() => void home.refetch()} />;
  const { context, counts, orders, attention } = home.data;
  const awaitingReceipt = orders.filter(order => ['DELIVERED', 'PARTIALLY_DELIVERED', 'AWAITING_RECEIPT'].includes(order.status) && !order.receiptStatus);
  const upcoming = orders.filter(order => !['RECEIPT_CONFIRMED', 'RECEIPT_ISSUE', 'DELIVERY_FAILED'].includes(order.status));
  const completed = orders.filter(order => order.status === 'RECEIPT_CONFIRMED');
  const featured = awaitingReceipt[0] || upcoming[0] || attention[0] || orders[0];
  const metrics = <section className="store-metric-grid" aria-label="Outlet order counts">{[
    { label: 'Upcoming orders', value: counts.upcoming, detail: 'Active delivery requests', Icon: Package, tone: 'blue' },
    { label: 'Deferred orders', value: counts.deferred, detail: 'Waiting for another run', Icon: Clock3, tone: 'amber' },
    { label: 'Awaiting receipt', value: counts.awaitingReceipt, detail: 'Check the delivered goods', Icon: CheckCircle2, tone: 'green' },
    { label: 'Needs attention', value: counts.attention, detail: 'Orders with open issues', Icon: TriangleAlert, tone: 'red' }
  ].map(metric => <div className="store-metric-card" key={metric.label}><div><span>{metric.label}</span><i className={metric.tone}><metric.Icon size={18} /></i></div><strong>{metric.value.toLocaleString()}</strong><small>{metric.detail}</small></div>)}</section>;
  return <div className="store-stack"><OutletIdentity outlet={context.outlet} context={context.operationalContext} /><div className="store-actions"><p className="store-helper">Delivery window {clockLabel(context.outlet.deliveryWindowOpen)}–{clockLabel(context.outlet.deliveryWindowClose)} · Sri Lanka time</p><Link className="btn primary" to="/store/place-order"><Plus size={17} />Place New Order</Link></div>{featured ? <FeaturedOrder order={featured} metrics={metrics} /> : <>{metrics}<Panel kicker="YOUR ORDERS" title="Ready for your first delivery request"><EmptyState title="No orders yet" message="Place an order for an operating day. Your request and every later handover will stay connected here."><Link className="btn primary" to="/store/place-order">Place Order<Plus size={17} /></Link></EmptyState></Panel></>}{awaitingReceipt.length > 0 && <Panel kicker="DELIVERED" title="Confirm the goods you received" action={<span className="store-chip amber">{counts.awaitingReceipt} awaiting receipt</span>}><div className="store-order-list">{awaitingReceipt.map(order => <OrderRow key={order.id} order={order} page="receipt" />)}</div></Panel>}{attention.length > 0 && <Panel kicker="REQUIRES ATTENTION" title="Keep these orders in view"><div className="store-order-list">{attention.map(order => <OrderRow key={order.id} order={order} />)}</div></Panel>}{orders.length > 0 && <Panel kicker="ORDER HISTORY" title="Recent orders" action={<Link className="store-text-link" to="/store/tracking">View tracking<ArrowRight size={15} /></Link>}><div className="store-order-list">{orders.slice(0, 8).map(order => <OrderRow key={order.id} order={order} />)}</div></Panel>}{completed.length > 0 && <Panel kicker="RECEIPT CONFIRMED" title="Recently completed" action={<span className="store-chip green">{counts.completed} completed</span>}><div className="store-order-list">{completed.slice(0, 4).map(order => <OrderRow key={order.id} order={order} />)}</div></Panel>}</div>;
}
