import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { Link } from 'react-router-dom';
import { ArrowRight, CheckCircle2, Clock3, Plus } from 'lucide-react';
import { storeOrderInputSchema, type StoreContext, type StoreOrderInput } from '@waypoint/shared';
import { createStoreOrder, STORE_KEYS } from './api';
import { dateLabel, orderLink, OutletIdentity, Panel, sentenceCase } from './components';

export function PlaceOrderPage({ context }: { context: StoreContext }) {
  const queryClient = useQueryClient();
  const schema = storeOrderInputSchema.superRefine((input, ctx) => {
    if (!context.operatingDates.includes(input.requestedDeliveryDate)) ctx.addIssue({ code: 'custom', path: ['requestedDeliveryDate'], message: 'Choose an available operating date.' });
    if (!context.temperatureRequirements.includes(input.temperatureRequirement)) ctx.addIssue({ code: 'custom', path: ['temperatureRequirement'], message: 'Choose a temperature supported by your outlet brand.' });
  });
  const form = useForm<StoreOrderInput>({ resolver: zodResolver(schema), mode: 'onTouched', defaultValues: { requestedDeliveryDate: context.nextEligibleDate || '', temperatureRequirement: context.temperatureRequirements[0] } });
  const mutation = useMutation({ mutationFn: createStoreOrder, onSuccess: async order => {
    queryClient.setQueryData(STORE_KEYS.order(order.id), order);
    await Promise.all([queryClient.invalidateQueries({ queryKey: STORE_KEYS.home }), queryClient.invalidateQueries({ queryKey: STORE_KEYS.orders })]);
  } });
  const selectedDate = form.watch('requestedDeliveryDate');
  const tomorrow = new Date(`${context.today}T00:00:00.000Z`); tomorrow.setUTCDate(tomorrow.getUTCDate() + 1);
  const lateNextDay = context.cutoffPassed && selectedDate === tomorrow.toISOString().slice(0, 10);
  const errors = form.formState.errors;
  return <div className="store-stack"><OutletIdentity outlet={context.outlet} context={context.operationalContext} /><div className="store-actions"><p className="store-helper">A request is created for your assigned outlet.</p><Link className="btn secondary" to="/store/home">Back to Home</Link></div>{mutation.isSuccess ? <Panel kicker="ORDER SAVED" title="Your order is confirmed" className="store-order-form-panel"><div className="store-panel-body"><div className="store-success" role="status"><CheckCircle2 size={24} /><div><strong>{mutation.data.orderRef}</strong><p>{mutation.data.orderedUnits.toLocaleString()} units · {sentenceCase(mutation.data.temperatureRequirement)} · awaiting planning</p></div></div><dl className="store-facts"><div><dt>Originally requested</dt><dd>{dateLabel(mutation.data.requestedDeliveryDate)}</dd></div><div><dt>Eligible delivery run</dt><dd>{dateLabel(mutation.data.eligibleDeliveryDate)}</dd></div></dl>{mutation.data.eligibilityNotice && <p className="store-note warning">{mutation.data.eligibilityNotice}</p>}<p className="store-note neutral">Your request is saved. A planned arrival will appear after a delivery plan is assigned.</p><div className="store-form-actions"><Link className="btn primary" to={orderLink(mutation.data)}>Track Delivery<ArrowRight size={17} /></Link><button className="btn secondary" type="button" onClick={() => { mutation.reset(); form.reset({ requestedDeliveryDate: context.nextEligibleDate || '', temperatureRequirement: context.temperatureRequirements[0] }); }}>Place another order<Plus size={16} /></button></div></div></Panel> : <Panel kicker={`${context.outlet.outletRef} · ${context.outlet.brand}`} title="New delivery request" action={<span className="store-chip blue"><Clock3 size={13} />Next-day cutoff 4 PM</span>} className="store-order-form-panel"><div className="store-panel-body"><p className="store-note neutral">{context.operationalContext} Orders close at 4:00 PM Sri Lanka time for the next day’s run.</p>{context.operatingDates.length === 0 ? <p className="store-note warning" role="alert">No future operating dates are available in the calendar. A delivery request cannot be submitted yet.</p> : <form className="store-form-grid" onSubmit={form.handleSubmit(input => mutation.mutate(input))} noValidate>
    <div className="field"><label htmlFor="order-date">Requested delivery date</label><select id="order-date" {...form.register('requestedDeliveryDate')} aria-invalid={!!errors.requestedDeliveryDate} aria-describedby="order-date-help order-date-error"><option value="">Choose an operating date</option>{context.operatingDates.map(date => <option key={date} value={date}>{dateLabel(date)}</option>)}</select><p className="store-helper" id="order-date-help">Available dates come from the operating calendar.</p>{errors.requestedDeliveryDate && <p className="field-error" id="order-date-error">{errors.requestedDeliveryDate.message}</p>}</div>
    <div className="field"><label htmlFor="order-temperature">Temperature requirement</label><select id="order-temperature" {...form.register('temperatureRequirement')} aria-invalid={!!errors.temperatureRequirement} aria-describedby={errors.temperatureRequirement ? 'order-temperature-error' : undefined}>{context.temperatureRequirements.map(temperature => <option key={temperature} value={temperature}>{sentenceCase(temperature)}</option>)}</select>{errors.temperatureRequirement && <p className="field-error" id="order-temperature-error">{errors.temperatureRequirement.message}</p>}{context.temperatureRequirements.length === 1 && <p className="store-helper">{sentenceCase(context.outlet.brand)} deliveries use ambient handling.</p>}</div>
    <div className="field"><label htmlFor="order-units">Requested units</label><input id="order-units" type="number" inputMode="numeric" min="1" step="1" placeholder="Enter units" {...form.register('orderedUnits', { valueAsNumber: true })} aria-invalid={!!errors.orderedUnits} aria-describedby={errors.orderedUnits ? 'order-units-error' : undefined} />{errors.orderedUnits && <p className="field-error" id="order-units-error">{errors.orderedUnits.message}</p>}</div>
    <div className="field"><label htmlFor="order-weight">Estimated weight (kg)</label><input id="order-weight" type="number" inputMode="decimal" min="0.001" step="0.001" placeholder="Enter weight" {...form.register('orderedWeightKg', { valueAsNumber: true })} aria-invalid={!!errors.orderedWeightKg} aria-describedby={errors.orderedWeightKg ? 'order-weight-error' : undefined} />{errors.orderedWeightKg && <p className="field-error" id="order-weight-error">{errors.orderedWeightKg.message}</p>}</div>
    <div className="field"><label htmlFor="order-volume">Estimated volume (m³)</label><input id="order-volume" type="number" inputMode="decimal" min="0.001" step="0.001" placeholder="Enter volume" {...form.register('orderedVolumeM3', { valueAsNumber: true })} aria-invalid={!!errors.orderedVolumeM3} aria-describedby={errors.orderedVolumeM3 ? 'order-volume-error' : undefined} />{errors.orderedVolumeM3 && <p className="field-error" id="order-volume-error">{errors.orderedVolumeM3.message}</p>}</div>
    {lateNextDay && <p className="store-note warning full" role="status">The next-day cutoff has passed. Your original requested date will stay recorded; the server will move eligibility to the next operating run{context.nextEligibleDate ? `, ${dateLabel(context.nextEligibleDate)}` : ' when one is available'}.</p>}
    {mutation.isError && <p className="error-notice full" role="alert">{mutation.error.message}</p>}
    <div className="store-form-actions full"><button className="btn primary" type="submit" disabled={mutation.isPending}>{mutation.isPending ? 'Saving order…' : 'Submit Order'}<ArrowRight size={17} /></button><Link className="btn secondary" to="/store/home">Cancel</Link></div>
  </form>}<p className="store-helper store-form-footnote">The server confirms calendar eligibility, cutoff and quantities when you submit.</p></div></Panel>}</div>;
}
