import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { Link } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, TriangleAlert } from 'lucide-react';
import { storeReceiptInputSchema, type StoreOrderDetail, type StoreReceiptInput } from '@waypoint/shared';
import { receiveStoreOrder, STORE_KEYS } from './api';
import { DeliveryEvidence, orderLink, OutletIdentity, Panel, Quantities, sentenceCase, StatusChip, timeLabel } from './components';
import { OrderSelection } from './OrderSelection';

function ReceiptForm({ order }: { order: StoreOrderDetail }) {
  const queryClient = useQueryClient();
  const schema = storeReceiptInputSchema.superRefine((input, ctx) => {
    if (input.receivedUnits !== order.deliveredUnits && (input.issueNote?.length ?? 0) < 5) ctx.addIssue({ code: 'custom', path: ['issueNote'], message: 'Explain the quantity difference in at least five characters.' });
  });
  const form = useForm<StoreReceiptInput>({ resolver: zodResolver(schema), mode: 'onTouched', defaultValues: { expectedVersion: order.version, receivedUnits: order.deliveredUnits ?? 0, issueType: 'NONE', issueNote: '' } });
  const mutation = useMutation({ mutationFn: (input: StoreReceiptInput) => receiveStoreOrder(order.id, input), onSuccess: async saved => {
    queryClient.setQueryData(STORE_KEYS.order(saved.id), saved);
    await Promise.all([queryClient.invalidateQueries({ queryKey: STORE_KEYS.home }), queryClient.invalidateQueries({ queryKey: STORE_KEYS.orders }), queryClient.invalidateQueries({ queryKey: STORE_KEYS.order(saved.id) })]);
  } });
  const received = form.watch('receivedUnits');
  const issueType = form.watch('issueType');
  const discrepancy = Number.isFinite(received) && received !== order.deliveredUnits;
  const isIssue = discrepancy || issueType !== 'NONE';
  const errors = form.formState.errors;
  return <form className="store-form-grid" onSubmit={form.handleSubmit(input => mutation.mutate(input))} noValidate><input type="hidden" {...form.register('expectedVersion', { valueAsNumber: true })} /><div className="field"><label htmlFor="receipt-quantity">Quantity actually received</label><input id="receipt-quantity" type="number" inputMode="numeric" min="0" step="1" {...form.register('receivedUnits', { valueAsNumber: true })} aria-invalid={!!errors.receivedUnits} aria-describedby={errors.receivedUnits ? 'receipt-quantity-error' : undefined} />{errors.receivedUnits && <p className="field-error" id="receipt-quantity-error">{errors.receivedUnits.message}</p>}</div><div className="field"><label htmlFor="receipt-condition">Condition / issue</label><select id="receipt-condition" {...form.register('issueType')}><option value="NONE">Received in good condition</option><option value="QUANTITY_DISCREPANCY">Quantity discrepancy</option><option value="DAMAGED_GOODS">Damaged goods</option><option value="OTHER">Other receipt issue</option></select></div>{isIssue && <div className="store-note warning full" role="status"><strong>{discrepancy ? 'Quantity difference detected' : 'Receipt issue reported'}</strong><p>{discrepancy ? `Driver delivered ${order.deliveredUnits?.toLocaleString()} units; you entered ${received.toLocaleString()} received.` : 'Describe the issue with the delivered goods.'} This will remain an open receipt issue for review.</p></div>}<div className={`field full ${isIssue ? 'store-discrepancy-field' : ''}`}><label htmlFor="receipt-note">Store receiving note {isIssue ? '(required)' : '(optional)'}</label><textarea id="receipt-note" rows={4} maxLength={1000} placeholder={isIssue ? 'Describe the missing quantity, damage or other issue.' : 'Add a useful receiving note.'} {...form.register('issueNote')} aria-invalid={!!errors.issueNote} aria-describedby={errors.issueNote ? 'receipt-note-error' : 'receipt-note-help'} /><p className="store-helper" id="receipt-note-help">{isIssue ? 'Include enough detail for the delivery team to review the issue.' : 'Confirm only after counting and checking the goods.'}</p>{errors.issueNote && <p className="field-error" id="receipt-note-error">{errors.issueNote.message}</p>}</div>{mutation.isError && <p className="error-notice full" role="alert">{mutation.error.message}</p>}<div className="full"><button className="btn primary store-block" type="submit" disabled={mutation.isPending}>{mutation.isPending ? 'Saving receipt…' : isIssue ? 'Report receipt issue' : 'Confirm Receipt'}{isIssue ? <TriangleAlert size={17} /> : <CheckCircle2 size={17} />}</button><p className="store-helper store-form-footnote">A quantity difference or reported issue keeps the order actionable.</p></div></form>;
}

function ReceiptDetail({ order }: { order: StoreOrderDetail }) {
  return <><OutletIdentity outlet={order.outlet} /><div className="store-actions"><p className="store-helper">Check the delivered goods before recording the Store receipt.</p><Link className="btn secondary" to={orderLink(order)}><ArrowLeft size={16} />Back to Tracking</Link></div><div className="store-receipt-layout"><Panel kicker={order.orderRef} title="Expected vs actual receipt" action={<StatusChip status={order.status} />}><div className="store-panel-body"><Quantities order={order} />{order.loadedUnits !== null && order.loadedUnits !== order.orderedUnits && <p className="store-note warning">The recorded load differs from the original request. Both quantities are retained.</p>}{order.receipt ? <><div className={`store-success ${order.receipt.status === 'ISSUE_REPORTED' ? 'issue' : ''}`} role="status">{order.receipt.status === 'ISSUE_REPORTED' ? <TriangleAlert size={24} /> : <CheckCircle2 size={24} />}<div><strong>{order.receipt.status === 'ISSUE_REPORTED' ? 'Receipt issue reported' : 'Receipt confirmed'}</strong><p>{order.receipt.receivedUnits.toLocaleString()} units received · {timeLabel(order.receipt.confirmedAt)}</p></div></div>{order.receipt.issueType && <p className="store-note warning"><strong>{sentenceCase(order.receipt.issueType)}</strong>{order.receipt.issueNote && <span>{order.receipt.issueNote}</span>}</p>}{!order.receipt.issueType && order.receipt.issueNote && <div className="store-driver-note"><span className="eyebrow">STORE RECEIVING NOTE</span><p>{order.receipt.issueNote}</p></div>}<p className="store-helper">{order.receipt.status === 'ISSUE_REPORTED' ? 'The issue is saved for review. This order has not been closed as a clean receipt.' : 'Your actual receipt quantity has been saved.'}</p></> : order.canReceive ? <ReceiptForm key={order.id} order={order} /> : <p className="store-note warning">{order.delivery ? 'This delivery is not currently eligible for receipt confirmation. Review its current state in tracking.' : 'Receipt confirmation is available after a driver records a delivery. Delivered quantity is not available yet.'}</p>}</div></Panel><aside><DeliveryEvidence order={order} /></aside></div></>;
}
export function ReceiptPage() { return <OrderSelection receipt>{order => <ReceiptDetail order={order} />}</OrderSelection>; }
