import type { ReactNode } from 'react';
import { Clock3, Package, TriangleAlert } from 'lucide-react';
import type { DispatcherTripSummary } from '@waypoint/shared';
export { clockLabel, dateLabel, sentenceCase, STATUS_LABELS, StatusChip, timeLabel } from '../store/components';

export function Panel({ kicker, title, action, children, className = '' }: { kicker?: string; title: string; action?: ReactNode; children: ReactNode; className?: string }) {
  return <section className={`dispatch-panel ${className}`}><div className="dispatch-panel-head"><div>{kicker && <span className="eyebrow">{kicker}</span>}<h2>{title}</h2></div>{action}</div>{children}</section>;
}
export function LoadingState({ message = 'Loading operational records…' }: { message?: string }) {
  return <section className="dispatch-state" role="status"><div className="loading-dot" /><h2>{message}</h2><p>Connecting to your permitted depot records.</p></section>;
}
export function ErrorState({ error, retry, children }: { error: Error; retry: () => void; children?: ReactNode }) {
  return <section className="dispatch-state"><TriangleAlert size={28} /><h2>Unable to load this view</h2><p role="alert">{error.message}</p><button className="btn primary" onClick={retry}>Try again</button>{children}</section>;
}
export function EmptyState({ title, message, children }: { title: string; message: string; children?: ReactNode }) {
  return <div className="dispatch-empty"><Package size={29} strokeWidth={1.5} /><h3>{title}</h3><p>{message}</p>{children}</div>;
}
export function SyntheticChip({ source }: { source: string }) { return source === 'SYNTHETIC' ? <span className="store-chip amber">SYNTHETIC</span> : null; }
export function tripProvenance(trip: DispatcherTripSummary) {
  return trip.planningOrigin === 'GENERATED' ? `Generated plan · ${trip.planningStatus ? trip.planningStatus.toLowerCase() : 'recorded state'}` : trip.planningOrigin === 'PREPARED' ? 'Prepared fixture · not generated by the allocator' : 'Planning origin not recorded';
}
export function StateChip({ value }: { value: string }) {
  const label = value.toLowerCase().replaceAll('_', ' ');
  const tone = ['OPEN', 'ISSUE_REPORTED', 'EXCEPTION', 'DELIVERY_FAILED'].includes(value) ? 'red' : ['RESOLVED', 'COMPLETED', 'CONFIRMED'].includes(value) ? 'green' : 'blue';
  return <span className={`store-chip ${tone}`}>{label[0].toUpperCase() + label.slice(1)}</span>;
}
export function Facts({ facts }: { facts: [string, ReactNode][] }) {
  return <dl className="dispatch-facts">{facts.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>;
}
export function UnknownGeography({ children }: { children?: ReactNode }) {
  return <div className="dispatch-network"><div className="dispatch-network-heading"><span><Clock3 size={21} /></span><div><strong>Network overview</strong><p>District and stop records · geographic position unavailable</p></div></div>{children}<p className="dispatch-network-note">Verified outlet coordinates are unavailable. This list shows persisted context without live GPS or invented locations.</p></div>;
}
export function Pagination({ page, limit, total, onPage }: { page: number; limit: number; total: number; onPage: (page: number) => void }) {
  const pages = Math.max(1, Math.ceil(total / limit));
  return <div className="dispatch-pagination"><span>{total === 0 ? '0 results' : `${((page - 1) * limit + 1).toLocaleString()}–${Math.min(page * limit, total).toLocaleString()} of ${total.toLocaleString()}`}</span><div><button className="btn secondary" disabled={page <= 1} onClick={() => onPage(page - 1)}>Previous</button><span>Page {page} of {pages}</span><button className="btn secondary" disabled={page >= pages} onClick={() => onPage(page + 1)}>Next</button></div></div>;
}
