import { Truck } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { PlanningRunDetail, PlanningTripDetail } from '@waypoint/shared';
import { EmptyState, Facts, Panel, StateChip, timeLabel, UnknownGeography } from './components';
import { dispatcherLink, useDispatcherParams } from './url';

function Capacity({ label, unit, value }: { label: string; unit: string; value: PlanningTripDetail['capacity']['weight'] }) {
  return <div className="dispatch-capacity"><div><strong>{label}</strong><span>{value.used} / {value.capacity} {unit}</span></div><div className="dispatch-capacity-track" role="meter" aria-label={`${label} used`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100, Math.max(0, value.percentage))} aria-valuetext={`${value.used} of ${value.capacity} ${unit}; ${value.remaining} remaining`}><span style={{ width: `${Math.min(100, Math.max(0, value.percentage))}%` }} /></div><small>{value.percentage.toFixed(1)}% used · {value.remaining} {unit} remaining</small></div>;
}

export function PlanTrips({ plan, selectedOrderId, selectOrder }: { plan: PlanningRunDetail | undefined; selectedOrderId: string | undefined; selectOrder: (id: string) => void }) {
  const { params } = useDispatcherParams();
  return <Panel kicker="PLANNING AREA" title={plan ? `${plan.summary.trips} planned trip groups` : 'No plan selected'} action={<Truck size={21} />}><div className="dispatch-panel-body"><UnknownGeography>{!plan ? <EmptyState title="Ready for a generated plan" message="Choose an operating day and depot, then Generate Plan. The engine records served and deferred decisions for eligible demand." /> : plan.trips.length === 0 ? <EmptyState title="No served trip in this run" message="Inspect deferred decisions and their recorded constraint reasons." /> : <div className="dispatch-generated-trips">{plan.trips.map(trip => <article className="dispatch-generated-trip" key={trip.id}><div className="dispatch-generated-trip-head"><div><strong>{trip.vehicle.vehicleRef} · Trip {trip.tripNumber}</strong><small>{trip.tripRef}</small></div><StateChip value={trip.status} /></div><Facts facts={[
    ['Departure', trip.plannedDeparture ? timeLabel(trip.plannedDeparture) : 'Not recorded'], ['Return', trip.plannedReturn ? timeLabel(trip.plannedReturn) : 'Not recorded'], ['Stops', String(trip.stopCount)], ['Estimated fuel', `${trip.estimatedFuelLitres} litres`]
  ]} /><Capacity label="Weight" unit="kg" value={trip.capacity.weight} /><Capacity label="Volume" unit="m³" value={trip.capacity.volume} /><ol className="dispatch-generated-stops">{trip.stops.map(stop => <li className={stop.orderId === selectedOrderId ? 'selected' : ''} key={stop.id}><span className="dispatch-stop-number">{stop.sequence}</span><div><button className="dispatch-reference-button" onClick={() => selectOrder(stop.orderId)}>{stop.outletRef}</button><small>{stop.orderRef}{!stop.active ? ' · Historical stop' : ''}</small><dl><div><dt>Arrival</dt><dd>{timeLabel(stop.plannedArrival)}</dd></div><div><dt>Service starts</dt><dd>{timeLabel(stop.plannedServiceStart)}</dd></div><div><dt>Service completes</dt><dd>{timeLabel(stop.plannedServiceComplete)}</dd></div><div><dt>Wait / service</dt><dd>{stop.plannedWaitingMinutes} / {stop.plannedServiceMinutes} min</dd></div></dl></div></li>)}</ol><Link className="dispatch-text-link" to={dispatcherLink('routes', params, { trip: trip.id, date: trip.serviceDate })}>Inspect trip record</Link></article>)}</div>}</UnknownGeography>{plan && <p className="dispatch-helper dispatch-footnote">Timing uses depot/district travel references and brand/dock service allowances. Travel between different districts conservatively combines both depot journeys; geographic route positions remain unavailable.</p>}{plan && <p className="dispatch-helper dispatch-footnote">{plan.status === 'DRAFT' ? 'Draft trip previews stay in planning until independent validation succeeds. Generation alone does not establish validity.' : plan.status === 'VALIDATED' ? 'Validated trips remain unreleased. Confirm release to make this plan available for loading.' : plan.status === 'RELEASED' ? 'This recorded plan has been released to loading.' : 'This superseded run is retained as planning history.'}</p>}</div></Panel>;
}
